Repository justifi-tech/web-component-library, pull requests merged in 2024-03, with the labels that each got.

#386 fix: style link was missing in examples
  apps/docs/stories/utils/code-examples.ts
Labels: documentation, dev QA

#392 Add default iframe-origin to bank-account-form and card-form components
  packages/webcomponents/src/components/bank-account-form/bank-account-form.tsx
  packages/webcomponents/src/components/bank-account-form/test/bank-account-form.spec.tsx
  packages/webcomponents/src/components/card-form/card-form.tsx
  packages/webcomponents/src/components/card-form/test/card-form.spec.tsx
Labels: bug, dev QA

#389 Fix country business form
  .changeset/polite-bears-sneeze.md
  packages/webcomponents/src/api/Business.ts
  packages/webcomponents/src/components/business-form/business-form.tsx
  packages/webcomponents/src/components/business-form/business-generic-info/business-generic-info.tsx
  packages/webcomponents/src/components/business-form/legal-address-form/legal-address-form.tsx
Labels: dev QA

#397 Release-03-06-24
  .changeset/polite-bears-sneeze.md
  packages/webcomponents/CHANGELOG.md
  packages/webcomponents/package.json
Labels: dev QA

#398 Add unit tests
  packages/webcomponents/src/components/form/form-control-text.tsx
  packages/webcomponents/src/components/form/test/__snapshots__/form-control-text.spec.tsx.snap
  packages/webcomponents/src/components/form/test/form-control-text.spec.tsx
Labels: dev QA

#396 Add FormController unit tests
  packages/webcomponents/src/components/form/test/form.spec.ts
Labels: dev QA

#395 Add unit tests for preventing bugs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dev QA

#403 remove chromatic workflow
  .github/workflows/chromatic-deployment.yaml
  apps/docs/package.json
Labels: dev QA

#402 Add form-control-datepart unit tests
  packages/webcomponents/src/components/form/form-control-datepart.tsx
  packages/webcomponents/src/components/form/test/__snapshots__/form-control-datepart.spec.tsx.snap
  packages/webcomponents/src/components/form/test/form-control-datepart.spec.tsx
Labels: dev QA

#401 Add form-control-monetary unit-tests
  packages/webcomponents/src/components/form/form-control-monetary.tsx
  packages/webcomponents/src/components/form/test/__snapshots__/form-control-monetary.spec.tsx.snap
  packages/webcomponents/src/components/form/test/form-control-monetary.spec.tsx
Labels: dev QA

#387 Reorganize components in sidebar
  apps/docs/.storybook/preview.ts
  apps/docs/.storybook/styles.css
  apps/docs/stories/changelog.stories.mdx
  apps/docs/stories/components/bank-account-form-docs.stories.mdx
  apps/docs/stories/components/bank-account-form.stories.tsx
  apps/docs/stories/components/business-details-docs.stories.mdx
  apps/docs/stories/components/business-details.stories.tsx
  apps/docs/stories/components/business-form-docs.stories.mdx
  apps/docs/stories/components/business-form-stepped-docs.stories.mdx
  apps/docs/stories/components/business-form-stepped.stories.tsx
  apps/docs/stories/components/business-form.stories.tsx
  apps/docs/stories/components/card-form-docs.stories.mdx
  apps/docs/stories/components/card-form.stories.tsx
  apps/docs/stories/components/gross-payment-chart-docs.stories.mdx
  apps/docs/stories/components/gross-payment-chart.stories.tsx
  apps/docs/stories/components/payment-details-docs.stories.mdx
  apps/docs/stories/components/payment-details.stories.tsx
  apps/docs/stories/components/payment-form-docs.stories.mdx
  apps/docs/stories/components/payment-form.stories.tsx
  apps/docs/stories/components/payments-list-docs.stories.mdx
  apps/docs/stories/components/payments-list.stories.tsx
  apps/docs/stories/components/payout-details-docs.stories.mdx
  apps/docs/stories/components/payout-details.stories.tsx
  apps/docs/stories/components/payouts-list-docs.stories.mdx
  apps/docs/stories/components/payouts-list.stories.tsx
  apps/docs/stories/frameworks/angular.stories.mdx
  apps/docs/stories/frameworks/react.stories.mdx
  apps/docs/stories/frameworks/vue.stories.mdx
Labels: dev QA

#338 Refactor gross payment chart decouple api calls
  packages/webcomponents/src/api/GrossVolume.ts
  packages/webcomponents/src/api/mockResponses/mockGrossVolumeReportSuccess.json
  packages/webcomponents/src/api/services/reports.service.ts
  packages/webcomponents/src/components/gross-payment-chart/get-gross-payment-chart-data.ts
  packages/webcomponents/src/components/gross-payment-chart/gross-payment-chart-core.tsx
  packages/webcomponents/src/components/gross-payment-chart/gross-payment-chart.tsx
  packages/webcomponents/src/components/gross-payment-chart/test/__snapshots__/gross-payment-chart-core.spec.tsx.snap
  packages/webcomponents/src/components/gross-payment-chart/test/__snapshots__/gross-payment-chart.spec.tsx.snap
  packages/webcomponents/src/components/gross-payment-chart/test/get-gross-payment-chart-data.spec.ts
  packages/webcomponents/src/components/gross-payment-chart/test/gross-payment-chart-core.spec.tsx
  packages/webcomponents/src/components/gross-payment-chart/test/gross-payment-chart.spec.tsx
Labels: dev QA

#400 Add form-control-number unit tests
  packages/webcomponents/src/components/form/form-control-number.tsx
  packages/webcomponents/src/components/form/test/__snapshots__/form-control-number.spec.tsx.snap
  packages/webcomponents/src/components/form/test/form-control-number.spec.tsx
Labels: dev QA

#415 Refact DetailSecion component
  packages/webcomponents/src/components/business-details/additional-questions-details/additional-questions-details.tsx
  packages/webcomponents/src/components/business-details/generic-info-details/generic-info-details.tsx
  packages/webcomponents/src/components/business-details/legal-address-details/legal-address-details.tsx
  packages/webcomponents/src/components/business-details/owner-details/owner-details.tsx
  packages/webcomponents/src/components/business-details/representative-details/representative-details.tsx
  packages/webcomponents/src/components/details/utils.tsx
  packages/webcomponents/src/components/payment-details/payment-details-core.tsx
  packages/webcomponents/src/components/payment-details/payment-details.tsx
  packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap
  packages/webcomponents/src/components/payout-details/payout-details-core.tsx
  packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap
  packages/webcomponents/src/components/subaccount-details/subaccount-account-details/subaccount-account-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-bank-details/subaccount-bank-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-merchant-details/subaccount-merchant-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-owners-details/subaccount-owners-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-representative-details/subaccount-representative-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-terms-details/subaccount-terms-details.tsx
Labels: dev QA

#420 Fix business details broken (#393)
  .changeset/rare-students-tell.md
  packages/webcomponents/src/components/business-details/additional-questions-details/additional-questions-details.tsx
  packages/webcomponents/src/components/business-details/business-details.tsx
  packages/webcomponents/src/components/business-details/generic-info-details/generic-info-details.tsx
  packages/webcomponents/src/components/business-details/legal-address-details/legal-address-details.tsx
  packages/webcomponents/src/components/business-details/owner-details/owner-details.tsx
  packages/webcomponents/src/components/business-details/representative-details/representative-details.tsx
  packages/webcomponents/src/utils/utils.ts
Labels: dev QA

#427 Adds a expiredToken event to the PaymentDetails
  .vscode/launch.json
  apps/docs/stories/components/payment-details-example.ts
  apps/docs/stories/components/payment-details.stories.tsx
  packages/webcomponents/package.json
  packages/webcomponents/src/api/services/__mocks__/payment.service.ts
  packages/webcomponents/src/api/shared.ts
  packages/webcomponents/src/components/payment-details/get-payment-details.ts
  packages/webcomponents/src/components/payment-details/payment-details-core.tsx
  packages/webcomponents/src/components/payment-details/payment-details.tsx
  packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap
  packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details.spec.tsx.snap
  packages/webcomponents/src/components/payment-details/test/get-payment-details.spec.ts
  packages/webcomponents/src/components/payment-details/test/payment-details-core.spec.tsx
  packages/webcomponents/src/components/payment-details/test/payment-details.spec.tsx
Labels: dev QA
