Repository justifi-tech/web-component-library, pull requests merged in 2024-02, with the labels that each got.

#332 Handle Business Form Errors
  packages/webcomponents/.changeset/config.json
  packages/webcomponents/.changeset/cuddly-fans-tap.md
  packages/webcomponents/src/components/business-form/business-form-stepped.tsx
  packages/webcomponents/src/components/business-form/business-form.scss
  packages/webcomponents/src/components/business-form/business-form.tsx
  packages/webcomponents/src/components/form/utils.tsx
Labels: dev QA

#351 Update bug report template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: dev QA

#353 Update business docs to omit references to account-id since it does n…
  .changeset/polite-ducks-kick.md
  apps/docs/stories/components/business-form-example.ts
  apps/docs/stories/components/business-form-stepped-example.ts
  apps/docs/stories/components/business-form-stepped.stories.tsx
  apps/docs/stories/components/business-form.stories.tsx
  packages/webcomponents/src/components/business-form/business-form-stepped.tsx
  packages/webcomponents/src/components/business-form/readme.md
Labels: documentation, dev QA

#356 refactor(card-form):tokenize response body
  .changeset/hungry-starfishes-move.md
  packages/webcomponents/src/components/payment-method-form/payment-method-responses.ts
Labels: dev QA

#359 BusinessForm "Country" input is disabled, required, and does not have a value
  .changeset/gentle-pots-whisper.md
  packages/webcomponents/src/api/BusinessV2.ts
  packages/webcomponents/src/components/business-form/legal-address-form/legal-address-form.tsx
Labels: bug, dev QA

#360 Prefill business generic info
  .changeset/poor-moose-smash.md
  packages/webcomponents/src/api/BusinessV2.ts
  packages/webcomponents/src/components/business-form/business-generic-info/business-generic-info.tsx
Labels: bug, dev QA

#365 Update business type file
  packages/webcomponents/src/api/Business.ts
  packages/webcomponents/src/api/BusinessV2.ts
  packages/webcomponents/src/components/business-details/additional-questions-details/additional-questions-details.tsx
  packages/webcomponents/src/components/business-details/business-details.tsx
  packages/webcomponents/src/components/business-form/business-form-stepped.tsx
  packages/webcomponents/src/components/business-form/business-form.tsx
  packages/webcomponents/src/components/business-form/business-generic-info/business-generic-info.tsx
Labels: dev QA

#367 Fix tax id field in business form
  packages/webcomponents/.changeset/nice-comics-yell.md
  packages/webcomponents/src/components/business-form/business-generic-info/business-generic-info.tsx
  packages/webcomponents/src/components/business-form/business-owners/business-owners.tsx
  packages/webcomponents/src/components/business-form/business-representative/business-representative.tsx
  packages/webcomponents/src/utils/form-input-masks.ts
Labels: dev QA

#331 refactor(PaymentsList): decouple api calls to improve testability
  packages/webcomponents/jest.config.js
  packages/webcomponents/package.json
  packages/webcomponents/src/api/Pagination.ts
  packages/webcomponents/src/api/Payment.ts
  packages/webcomponents/src/api/mockData/MockPayments.ts
  packages/webcomponents/src/api/mockData/mockPaymentsSuccess.json
  packages/webcomponents/src/api/services/payment.service.ts
  packages/webcomponents/src/api/services/utils.ts
  packages/webcomponents/src/components/details/utils.tsx
  packages/webcomponents/src/components/pagination-menu/test/pagination-menu.spec.tsx
  packages/webcomponents/src/components/payments-list/get-payments.ts
  packages/webcomponents/src/components/payments-list/payments-list-core.tsx
  packages/webcomponents/src/components/payments-list/payments-list.tsx
  packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap
  packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list.spec.tsx.snap
  packages/webcomponents/src/components/payments-list/test/get-payments.spec.ts
  packages/webcomponents/src/components/payments-list/test/payments-list-core.spec.tsx
  packages/webcomponents/src/components/payments-list/test/payments-list.spec.tsx
  packages/webcomponents/src/components/table/table.tsx
  packages/webcomponents/src/components/table/test/table.spec.tsx
  packages/webcomponents/src/components/table/utils.tsx
  pnpm-lock.yaml
Labels: enhancement, dev QA

#370 adds a delay for chromatic screenshot
  apps/docs/stories/components/payment-form.stories.tsx
Labels: dev QA

#363 Business form events
  apps/docs/stories/components/business-form-stepped.stories.tsx
  apps/docs/stories/components/business-form.stories.tsx
  packages/webcomponents/.changeset/beige-suns-drop.md
  packages/webcomponents/src/components/business-form/BusinessFormEventTypes.ts
  packages/webcomponents/src/components/business-form/business-form-stepped.tsx
  packages/webcomponents/src/components/business-form/business-form.tsx
  packages/webcomponents/src/components/business-form/helpers.ts
Labels: dev QA

#335 refactor(PaymentDetails): create payment-details-core component
  packages/webcomponents/src/api/mockData/mockPaymentDetailSuccess.json
  packages/webcomponents/src/api/services/payment.service.ts
  packages/webcomponents/src/components/payment-details/get-payment-details.ts
  packages/webcomponents/src/components/payment-details/payment-details-core.tsx
  packages/webcomponents/src/components/payment-details/payment-details.tsx
  packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap
  packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details.spec.tsx.snap
  packages/webcomponents/src/components/payment-details/test/get-payment-details.spec.ts
  packages/webcomponents/src/components/payment-details/test/payment-details-core.spec.tsx
  packages/webcomponents/src/components/payment-details/test/payment-details.spec.tsx
Labels: dev QA

#340 Closes justifi-tech/web-component-library#339
  apps/docs/.storybook/main.ts
  apps/docs/public/favicon.ico
Labels: dev QA

#369 Update the example for the payments form
  apps/docs/stories/components/payment-form-example.ts
Labels: dev QA

#336 refactor(PayoutDetails): create payout-details-core component
  packages/webcomponents/src/api/mockData/mockPayoutDetailsSuccess.json
  packages/webcomponents/src/api/services/payout.service.ts
  packages/webcomponents/src/components/payout-details/get-payout-details.ts
  packages/webcomponents/src/components/payout-details/payout-details-core.tsx
  packages/webcomponents/src/components/payout-details/payout-details.tsx
  packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap
  packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details.spec.tsx.snap
  packages/webcomponents/src/components/payout-details/test/get-payout-details.spec.ts
  packages/webcomponents/src/components/payout-details/test/payout-details-core.spec.tsx
  packages/webcomponents/src/components/payout-details/test/payout-details.spec.tsx
Labels: dev QA

#373 fix directory path
  .github/workflows/test.yaml
Labels: dev QA

#376 Update business form docs
  apps/docs/stories/components/business-form-example.ts
  apps/docs/stories/components/business-form.stories.tsx
Labels: dev QA

#383 Add default fallback of 'USA' to legal address country for business c…
  .changeset/quiet-dryers-notice.md
  packages/webcomponents/src/api/Business.ts
  packages/webcomponents/src/components/business-details/legal-address-details/legal-address-details.tsx
  packages/webcomponents/src/components/business-form/legal-address-form/legal-address-form.tsx
Labels: dev QA

#380 refactor: payment-form and unit tests
  packages/webcomponents/src/components/bank-account-form/bank-account-form.tsx
  packages/webcomponents/src/components/card-form/card-form.tsx
  packages/webcomponents/src/components/payment-form/payment-form.tsx
  packages/webcomponents/src/components/payment-form/payment-method-selector.tsx
  packages/webcomponents/src/components/payment-form/test/payment-form.spec.tsx
  packages/webcomponents/src/components/payment-method-form/payment-method-form.tsx
  packages/webcomponents/src/components/payment-method-form/test/payment-method-form.spec.tsx
  packages/webcomponents/src/utils/frame-comunication-service.ts
  packages/webcomponents/src/utils/get-computed-theme.ts
  packages/webcomponents/src/utils/theme.ts
  packages/webcomponents/src/utils/utils.ts
Labels: dev QA
