Repository justifi-tech/web-component-library, pull requests merged in 2024-09, with the labels that each got.

#655 Theme PaymentProvisioning and put it on a card in storybook
  .changeset/four-tips-prove.md
  apps/docs/.storybook/manager.css
  apps/docs/.storybook/manager.ts
  apps/docs/.storybook/storybookTheme.ts
  apps/docs/stories/components/PaymentProvisioning/Docs.mdx
  apps/docs/stories/components/PaymentProvisioning/index.stories.tsx
  apps/docs/stories/themes/dark.ts
  apps/docs/stories/themes/light.ts
  apps/docs/stories/utils/decorators.ts
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.css
  packages/webcomponents/src/components/checkout/checkout-core.tsx
  packages/webcomponents/src/components/checkout/test/__snapshots__/checkout-core.spec.tsx.snap
  packages/webcomponents/src/components/checkout/test/__snapshots__/checkout.spec.tsx.snap
  packages/webcomponents/src/components/form/form-control-monetary.tsx
  packages/webcomponents/src/components/form/test/__snapshots__/form-control-monetary.spec.tsx.snap
  packages/webcomponents/src/styles/root.css
Labels: dev QA

#661 Parse associated_accounts from business payload
  .changeset/famous-steaks-tickle.md
  packages/webcomponents/src/components/business-forms/utils/payload-parsers.ts
Labels: dev QA

#666 Update value for mock business details tax_id
  mockData/mockBusinessDetails.json
  packages/webcomponents/src/components/business-details/generic-info-details/test/__snapshots__/generic-info-details.spec.tsx.snap
Labels: dev QA

#653 add date range filter on payments/payouts table
  .changeset/blue-bottles-watch.md
  apps/docs/stories/components/PaymentsList/index.stories.tsx
  apps/docs/stories/components/PayoutsList/index.stories.tsx
  packages/webcomponents/src/components/form/readme.md
  packages/webcomponents/src/components/payments-list/payments-list-core.tsx
  packages/webcomponents/src/components/payments-list/payments-list.tsx
  packages/webcomponents/src/components/payments-list/readme.md
  packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap
  packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx
  packages/webcomponents/src/components/payouts-list/payouts-list.tsx
  packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list-core.spec.tsx.snap
Labels: dev QA

#656 add download CSV button for payout details and list
  .changeset/old-baboons-wonder.md
  packages/webcomponents/src/api/services/payout.service.ts
  packages/webcomponents/src/assets/download-icon.tsx
  packages/webcomponents/src/components/payout-details/get-payout-csv.ts
  packages/webcomponents/src/components/payout-details/payout-details-core.tsx
  packages/webcomponents/src/components/payout-details/payout-details.tsx
  packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap
  packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx
  packages/webcomponents/src/components/payouts-list/payouts-list.tsx
  packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list-core.spec.tsx.snap
Labels: dev QA

#664 delete components and related files
  packages/webcomponents/src/api/Payment.ts
  packages/webcomponents/src/api/Proceed.ts
  packages/webcomponents/src/api/SubAccount.ts
  packages/webcomponents/src/components/business-list/Docs.stories.mdx
  packages/webcomponents/src/components/business-list/business-list.stories.ts
  packages/webcomponents/src/components/business-list/business-list.tsx
  packages/webcomponents/src/components/business-list/example.js
  packages/webcomponents/src/components/business-list/readme.md
  packages/webcomponents/src/components/details/readme.md
  packages/webcomponents/src/components/payment-balance-transactions/payment-balance-transactions.stories.ts
  packages/webcomponents/src/components/payment-balance-transactions/payment-balance-transactions.tsx
  packages/webcomponents/src/components/payment-balance-transactions/readme.md
  packages/webcomponents/src/components/proceeds-list/Docs.stories.mdx
  packages/webcomponents/src/components/proceeds-list/example.js
  packages/webcomponents/src/components/proceeds-list/proceeds-list.stories.ts
  packages/webcomponents/src/components/proceeds-list/proceeds-list.tsx
  packages/webcomponents/src/components/proceeds-list/readme.md
  packages/webcomponents/src/components/subaccount-details/readme.md
  packages/webcomponents/src/components/subaccount-details/subaccount-account-details/readme.md
  packages/webcomponents/src/components/subaccount-details/subaccount-account-details/subaccount-account-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-bank-details/readme.md
  packages/webcomponents/src/components/subaccount-details/subaccount-bank-details/subaccount-bank-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-details.stories.ts
  packages/webcomponents/src/components/subaccount-details/subaccount-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-merchant-details/readme.md
  packages/webcomponents/src/components/subaccount-details/subaccount-merchant-details/subaccount-merchant-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-owners-details/readme.md
  packages/webcomponents/src/components/subaccount-details/subaccount-owners-details/subaccount-owners-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-representative-details/readme.md
  packages/webcomponents/src/components/subaccount-details/subaccount-representative-details/subaccount-representative-details.tsx
  packages/webcomponents/src/components/subaccount-details/subaccount-terms-details/readme.md
  packages/webcomponents/src/components/subaccount-details/subaccount-terms-details/subaccount-terms-details.tsx
  packages/webcomponents/src/components/subaccount-details/test/__snapshots__/subaccount-details.spec.tsx.snap
  packages/webcomponents/src/components/subaccount-details/test/subaccount-details.spec.tsx
  packages/webcomponents/src/components/subaccounts-list/readme.md
  packages/webcomponents/src/components/subaccounts-list/subaccounts-list.css
  packages/webcomponents/src/components/subaccounts-list/subaccounts-list.stories.ts
  packages/webcomponents/src/components/subaccounts-list/subaccounts-list.tsx
  packages/webcomponents/src/components/subaccounts-list/test/subaccounts-list.e2e.ts
  packages/webcomponents/src/components/subaccounts-list/test/subaccounts-list.spec.tsx
  packages/webcomponents/src/components/table/readme.md
  packages/webcomponents/src/utils/utils.ts
Labels: dev QA

#668 add analytics to insurance component
  .changeset/many-hairs-grab.md
  packages/webcomponents/src/components/insurance/season-interruption/season-interruption-insurance.tsx
Labels: dev QA

#667 Payment provisioning custom style cleanup
  .changeset/bright-trains-wonder.md
  apps/docs/stories/components/PaymentForm/index.stories.tsx
  apps/docs/stories/themes/dark.ts
  apps/docs/stories/themes/light.ts
  packages/webcomponents/src/components/billing-form/billing-form.tsx
  packages/webcomponents/src/components/business-details/business-details-core.tsx
  packages/webcomponents/src/components/business-details/test/__snapshots__/busines-details-core.spec.tsx.snap
  packages/webcomponents/src/components/business-details/test/busines-details-core.spec.tsx
  packages/webcomponents/src/components/business-forms/business-form/business-form.tsx
  packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-documents-on-file.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-form-buttons.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.css
  packages/webcomponents/src/components/checkout/checkout-core.tsx
  packages/webcomponents/src/components/checkout/test/__snapshots__/checkout-core.spec.tsx.snap
  packages/webcomponents/src/components/checkout/test/__snapshots__/checkout.spec.tsx.snap
  packages/webcomponents/src/components/checkout/test/checkout-core.spec.tsx
  packages/webcomponents/src/components/checkout/test/checkout.spec.tsx
  packages/webcomponents/src/components/details/details.tsx
  packages/webcomponents/src/components/form/utils.tsx
  packages/webcomponents/src/components/insurance/season-interruption/season-interruption-insurance-core.tsx
  packages/webcomponents/src/components/insurance/season-interruption/test/__snapshots__/season-interruption-insurance-core.spec.tsx.snap
  packages/webcomponents/src/components/insurance/season-interruption/test/__snapshots__/season-interruption-insurance.spec.tsx.snap
  packages/webcomponents/src/components/insurance/season-interruption/test/season-interruption-insurance-core.spec.tsx
  packages/webcomponents/src/components/insurance/season-interruption/test/season-interruption-insurance.spec.tsx
  packages/webcomponents/src/components/payment-details/payment-details-core.tsx
  packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap
  packages/webcomponents/src/components/payment-details/test/payment-details-core.spec.tsx
  packages/webcomponents/src/components/payment-form/payment-form.tsx
  packages/webcomponents/src/components/payment-form/test/__snapshots__/payment-form.spec.tsx.snap
  packages/webcomponents/src/components/payment-form/test/payment-form.spec.tsx
  packages/webcomponents/src/components/payments-list/payments-list-core.tsx
  packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap
  packages/webcomponents/src/components/payments-list/test/payments-list-core.spec.tsx
  packages/webcomponents/src/components/payout-details/payout-details-core.tsx
  packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap
  packages/webcomponents/src/components/payout-details/test/payout-details-core.spec.tsx
  packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx
  packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list-core.spec.tsx.snap
  packages/webcomponents/src/components/payouts-list/test/payouts-list-core.spec.tsx
  packages/webcomponents/src/components/refund-form/refund-form.tsx
  packages/webcomponents/src/styles/root.css
  packages/webcomponents/src/ui-components/button-spinner.tsx
  packages/webcomponents/src/ui-components/button.tsx
  packages/webcomponents/src/ui-components/index.ts
  packages/webcomponents/src/ui-components/styled-host/modified-bootstrap.css
  packages/webcomponents/src/ui-components/styled-host/styled-host.tsx
Labels: dev QA

#673 Improve mock data and user experience testing provisioning form
  .changeset/long-colts-cross.md
  apps/docs/stories/utils/mockAllServices.ts
  mockData/mockBusinessDetails.json
  mockData/mockBusinessProvisioningSuccess.json
  mockData/mockBusinessTermsSuccess.json
  mockData/mockDocumentRecordSuccess.json
  packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-form-step.tsx
Labels: dev QA

#658 Removes the justifi-table component from payments-list
  packages/webcomponents/src/components/pagination-menu/readme.md
  packages/webcomponents/src/components/payments-list/payments-list-core.tsx
  packages/webcomponents/src/components/payments-list/readme.md
  packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap
  packages/webcomponents/src/components/payments-list/test/payments-list-core.spec.tsx
  packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx
  packages/webcomponents/src/components/payouts-list/readme.md
  packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list-core.spec.tsx.snap
  packages/webcomponents/src/components/payouts-list/test/payouts-list-core.spec.tsx
  packages/webcomponents/src/components/table/readme.md
  packages/webcomponents/src/components/table/table.css
  packages/webcomponents/src/components/table/table.tsx
  packages/webcomponents/src/components/table/test/table.spec.tsx
  packages/webcomponents/src/components/table/utils.tsx
  packages/webcomponents/src/styles/root.css
  packages/webcomponents/src/ui-components/index.ts
  packages/webcomponents/src/ui-components/table-empty-state.tsx
  packages/webcomponents/src/ui-components/table-error-state.tsx
  packages/webcomponents/src/ui-components/table-loading-state.tsx
Labels: dev QA

#646 Refactor owners form core component
  packages/mockData/mockGrossVolumeReport.js
  packages/webcomponents/src/api/services/business.service.ts
  packages/webcomponents/src/components/business-forms/owner-form/identity-address/readme.md
  packages/webcomponents/src/components/business-forms/owner-form/owner-form-core.tsx
  packages/webcomponents/src/components/business-forms/owner-form/owner-form-inputs.tsx
  packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/readme.md
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-actions.ts
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-form-steps.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/readme.md
  packages/webcomponents/src/components/business-forms/utils/business-form-types.ts
  packages/webcomponents/src/components/form/form-control-number-masked.tsx
  packages/webcomponents/src/components/form/readme.md
  packages/webcomponents/src/ui-components/button.tsx
Labels: dev QA

#672 Remove PaymentForm, CardForm, and BankAccountForm from Storybook
  apps/docs/stories/components/BankAccountForm/Docs.mdx
  apps/docs/stories/components/BankAccountForm/example.ts
  apps/docs/stories/components/BankAccountForm/index.stories.tsx
  apps/docs/stories/components/CardForm/Docs.mdx
  apps/docs/stories/components/CardForm/example.ts
  apps/docs/stories/components/CardForm/index.stories.tsx
  apps/docs/stories/components/Checkout/index.stories.tsx
  apps/docs/stories/components/GrossPaymentChart/Docs.mdx
  apps/docs/stories/components/GrossPaymentChart/index.stories.tsx
  apps/docs/stories/components/PaymentDetails/Docs.mdx
  apps/docs/stories/components/PaymentDetails/index.stories.tsx
  apps/docs/stories/components/PaymentForm/Docs.mdx
  apps/docs/stories/components/PaymentForm/example.ts
  apps/docs/stories/components/PaymentForm/index.stories.tsx
  apps/docs/stories/components/PaymentsList/Docs.mdx
  apps/docs/stories/components/PaymentsList/index.stories.tsx
  apps/docs/stories/components/PayoutDetails/Docs.mdx
  apps/docs/stories/components/PayoutDetails/index.stories.tsx
  apps/docs/stories/components/PayoutsList/Docs.mdx
  apps/docs/stories/components/PayoutsList/index.stories.tsx
Labels: documentation, dev QA

#676 Payment provisioning component form steps render refactor
  .changeset/lemon-waves-kick.md
  packages/webcomponents/src/api/services/business.service.ts
  packages/webcomponents/src/components/business-forms/owner-form/identity-address/readme.md
  packages/webcomponents/src/components/business-forms/owner-form/owner-form-core.tsx
  packages/webcomponents/src/components/business-forms/owner-form/owner-form-inputs.tsx
  packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/readme.md
  packages/webcomponents/src/components/business-forms/payment-provisioning/bank-account/business-bank-account-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/readme.md
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/readme.md
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/README.md
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-inputs.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-input-group.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/readme.md
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-actions.ts
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-form-steps.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/readme.md
  packages/webcomponents/src/components/business-forms/payment-provisioning/terms-and-conditions/business-terms-conditions-form-step.tsx
  packages/webcomponents/src/components/business-forms/utils/business-form-types.ts
  packages/webcomponents/src/components/business-forms/utils/input-handlers.ts
  packages/webcomponents/src/components/form/form-control-number-masked.tsx
  packages/webcomponents/src/components/form/readme.md
Labels: dev QA

#681 fix style bug on Safari
  .changeset/fluffy-spies-enjoy.md
  packages/webcomponents/src/components/payment-method-form/payment-method-form.tsx
  packages/webcomponents/src/components/payment-method-form/test/payment-method-form.spec.tsx
Labels: bug, dev QA

#682 Put back PaymentForm
  apps/docs/stories/components/PaymentForm/Docs.mdx
  apps/docs/stories/components/PaymentForm/example.ts
  apps/docs/stories/components/PaymentForm/index.stories.tsx
Labels: dev QA

#679 Update Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dev QA

#683 Fix Button ui-component width
  packages/webcomponents/src/components/business-forms/owner-form/owner-form-core.tsx
  packages/webcomponents/src/components/checkout/checkout-core.tsx
  packages/webcomponents/src/components/checkout/test/__snapshots__/checkout-core.spec.tsx.snap
  packages/webcomponents/src/components/checkout/test/__snapshots__/checkout.spec.tsx.snap
  packages/webcomponents/src/components/payment-form/payment-form.tsx
  packages/webcomponents/src/components/payment-form/test/__snapshots__/payment-form.spec.tsx.snap
  packages/webcomponents/src/styles/root.css
Labels: dev QA

#687 4.19.0 release
  .changeset/bright-trains-wonder.md
  .changeset/fluffy-spies-enjoy.md
  .changeset/lemon-waves-kick.md
  .changeset/long-colts-cross.md
  .changeset/many-hairs-grab.md
  apps/docs/CHANGELOG.md
  apps/docs/package.json
  packages/webcomponents/CHANGELOG.md
  packages/webcomponents/package.json
Labels: dev QA

#697 Remove payload parsers and add payload getter to classes
  packages/webcomponents/src/api/Business.ts
  packages/webcomponents/src/api/Identity.ts
  packages/webcomponents/src/components/business-forms/business-form/business-form.tsx
  packages/webcomponents/src/components/business-forms/owner-form/owner-form-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-form-step.tsx
  packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step-core.tsx
  packages/webcomponents/src/components/business-forms/utils/payload-parsers.ts
Labels: dev QA
